version: "2"

services:
  rasa:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ./entrypoint.sh
    ports:
      - "5002:5002"
      - "5005:5005"
      # http://localhost:5002/api
    depends_on:
      - action_server
    env_file:
      - ./backend/.env
    container_name: rasa-wrapper

  action_server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ./action_entrypoint.sh
    container_name: action_server
    environment:
      - MYSQL_HOST=some-mariadb
    ports:
      - "5055:5055"
    depends_on:
      - some-mariadb

  some-mariadb:
    image: mariadb:10.6 
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./backend/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    stdin_open: true
    tty: true
    depends_on:
      - rasa
